# Generated by Django 3.0.6 on 2020-06-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200627_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
