# Generated by Django 3.0.6 on 2020-06-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200627_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(db_index=True, default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='cost',
            field=models.FloatField(default=1, verbose_name='Cost'),
        ),
    ]
