# Generated by Django 3.0.6 on 2020-06-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200628_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='is_canceled',
        ),
        migrations.AddField(
            model_name='return',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='return',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
