# Generated by Django 3.0.6 on 2020-06-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200628_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
