# Generated by Django 3.0.6 on 2020-06-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_purchase_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='canceled_at',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='cost',
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(db_index=True, default=False, verbose_name='В наличии'),
        ),
    ]
