# Generated by Django 3.0.6 on 2020-06-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200630_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='status',
        ),
    ]
