# Generated by Django 3.0.6 on 2020-06-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_return_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'NEW'), (2, 'IN_PROCESSING'), (3, 'DECLINED'), (4, 'APPROVED'), (5, 'SUCCESS')], default=1),
        ),
    ]
